# Config file for automatic testing at travis-ci.com

language: python

# workaround to get Python 3.7
sudo: required
dist: xenial

python:
    - 3.7
    - 3.6

# command to install dependencies
install:
    - pip install flit pytest pytest-cov
    - flit install

# command to run tests
script:
    - make test-ci