# Config file for automatic testing at travis-ci.com

language: python
python:
    - 3.7
    - 3.6

# command to install dependencies
install:
    - pip install flit pytest pytest-cov
    - flit install

# command to run tests
script:
    - make test-ci